apiVersion: v1
kind: ConfigMap
metadata:
  name: twreport-mailer-appsettings
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "twreport.labels" . | nindent 4 }}
data:
  appsettings.json: {{ .Values.appsettings | toJson | quote }}
