apiVersion: v1
kind: Secret
metadata:
  name: twreport-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "twreport.labels" . | nindent 4 }}
type: Opaque
stringData:
  resend-api-key: {{ .Values.resendApiKey | quote }}
