apiVersion: v1
kind: Secret
metadata:
  name: twreport-taskrc-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "twreport.labels" . | nindent 4 }}
type: Opaque
stringData:
  taskrc-secret: |
    sync.server.client_id={{ .Values.taskrcSecret.clientId }}
    sync.encryption_secret={{ .Values.taskrcSecret.encryptionSecret }}
