apiVersion: v1
kind: ConfigMap
metadata:
  name: twreport-taskrc
data:
  taskrc: |
    news.version=3.4.2
    editor=nvim
    report.next.filter=status:pending -WAITING limit:6
    uda.priority.default=M
    sync.server.url=https://taskchampion.home.kennethlieyanto.com
    context.d.read=-work
    context.work.read=+work
    context.work.write=+work
    context.homeserver.read=proj:homeserver
    context.homeserver.write=proj:homeserver
    context.actual-budget.read=proj:homeserver +actualbudget
    context.actual-budget.write=proj:homeserver +actualbudget
    context.k3s.read=proj:homeserver +k3s
    context.k3s.write=proj:homeserver +k3s
    context.actualbudget.read=proj:homeserver +actualbudget
